apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: checker
            image: bitnami/kubectl
            command:
            - /bin/sh
            - -c
            - kubectl get pods --all-namespaces | grep -v Running
          restartPolicy: OnFailure
